use std::{fs, path::PathBuf};
use fluent_syntax::parser;
use fluent_syntax::ast;

fn main() {
    let ftl_path = "src/locales/en/strings.ftl";

    // 1. Tell Cargo to re-run the script if the FTL file changes
    println!("cargo:rerun-if-changed={}", ftl_path);

    let source = fs::read_to_string(ftl_path).expect("Failed to read FTL source file.");
    let resource = parser::parse(source).expect("Failed to parse FTL file syntax.");

    let mut code = String::from("//! This file is automatically generated by build.rs\n\n");
    code.push_str("pub mod strings {\n");

    // 2. Iterate through all entries in the parsed AST
    for entry in resource.body {
        // Only process Message entries (which hold the translation key/ID)
        if let ast::Entry::Message(msg) = entry {
            let key = &msg.id.name;

            // 3. Format the key name (e.g., "app-title" -> "APP_TITLE")
            let const_name = key.replace("-", "_").to_uppercase();

            code.push_str(&format!(
                "    pub const {}: &str = \"{}\";\n", const_name, key
            ));
        }
    }
    code.push_str("}\n");

    // 5. Write the generated code to the output directory
    let out_dir = "src";
    let dest_path = PathBuf::from(out_dir).join("string_keys.rs");
    fs::write(dest_path, code).unwrap();
}